### ISSUE TITLE
Hotkeys often still interpreted by Windows 10

### ISSUE THREAD

**Issue by cmprmsd** [ritschmaster/b3#10]
How may I disable all Windows 10 hotkeys?
Is it possible to somehow change the implementation when I press different hotkeys in a row?

E.g. when I switch between tiles and then want to move a tile to any direction the Windows hotkey is recognized and does whatever is configured by Windows on this hotkey.

**Comment by ritschmaster** [comment]
Please have a look at the following links:
* https://github.com/ritschmaster/w32bindkeys#i-want-to-remap-the-win-key
* https://github.com/ritschmaster/w32bindkeys#any-cool-hacks-you-know-of


But you cannot disable **all** Windows hotkeys (e.g. Win + 1 shows the first application in the task bar). At least currently. You can have a look [here](https://github.com/ritschmaster/w32bindkeys#are-there-known-limitations) to understand why.

One way to increase the possibility of overriding the keys is to increase the priority of b3 in the Task Manager.

Maybe someone (you?) can find a way to consistently override the Windows hotkeys.

**Comment by codycraven** [comment]
I was able to prevent this issue by disabling all win+_ hotkeys.

I used Group Policy Editor to disable all win+_ hotkeys other than win+L
![image](https://user-images.githubusercontent.com/1533965/140633901-4c1d5ad9-05bb-4426-82e5-1cbeecc9110b.png)

I then used a registry hack to disable win+L, at the cost of no longer being able to lock my machine.

I'm not sure if I'll keep it, yet, but I couldn't get any other key to work decently (I fought way too long with alt/Mod1 since windows uses that for accessing application menus and couldn't figure out how to disable that behavior)

**Comment by ritschmaster** [comment]
I am closing this as this is a common and known issue in the Win32 Keyboard Hook. If anyone finds a solution to this then I am happy to accept any pull request.
